-- V1.1 national station lookup, city aliases and persistent verification highlights.
-- Production is PostgreSQL; public.attendees is the canonical participant table.

alter table public.attendees add column if not exists verify_highlight_fields jsonb not null default '[]'::jsonb;
alter table public.attendees disable trigger attendees_audit_change;
update public.attendees
set verify_highlight_fields=coalesce(custom_fields->'_travelVerifiedHighlights','[]'::jsonb)
where verify_highlight_fields='[]'::jsonb and jsonb_typeof(custom_fields->'_travelVerifiedHighlights')='array';
alter table public.attendees enable trigger attendees_audit_change;

create or replace function public.normalize_station_text(p_value text)
returns text language sql immutable parallel safe as $$
  select btrim(regexp_replace(replace(replace(replace(replace(replace(coalesce(p_value,''),chr(8203),''),chr(8204),''),chr(8205),''),chr(65279),''),chr(12288),' '),'\s+',' ','g'))
$$;

create table if not exists public.city_alias(
  id bigint generated by default as identity primary key,
  alias_name text not null,
  standard_city_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(alias_name)
);
alter table public.city_alias enable row level security;
grant select on public.city_alias to authenticated;
grant all on public.city_alias to service_role;
grant usage,select on sequence public.city_alias_id_seq to authenticated,service_role;
drop policy if exists city_alias_read on public.city_alias;
create policy city_alias_read on public.city_alias for select to authenticated using(true);
drop policy if exists city_alias_admin_write on public.city_alias;
create policy city_alias_admin_write on public.city_alias for all to authenticated using(public.is_system_admin()) with check(public.is_system_admin());

update public.station_dict set
  city_name=public.normalize_station_text(city_name),
  station_name=public.normalize_station_text(station_name),
  station_short_name=coalesce(nullif(public.normalize_station_text(station_short_name),''),public.normalize_station_text(station_name));
alter table public.station_dict alter column station_short_name set not null;
grant select on public.station_dict to authenticated;
grant all on public.station_dict to service_role;

create or replace function public.guard_station_dictionary()
returns trigger language plpgsql as $$
begin
  new.city_name:=regexp_replace(public.normalize_station_text(new.city_name),'市$','');
  new.station_name:=public.normalize_station_text(new.station_name);
  new.station_short_name:=coalesce(nullif(public.normalize_station_text(new.station_short_name),''),new.station_name);
  if new.city_name='' or new.station_name='' or new.transport_type not in('PLANE','HIGH_SPEED_RAIL') then raise exception '场站字典数据无效'; end if;
  new.updated_at:=now();return new;
end; $$;
drop trigger if exists station_dict_normalize on public.station_dict;
create trigger station_dict_normalize before insert or update on public.station_dict for each row execute function public.guard_station_dictionary();

create or replace function public.guard_city_alias()
returns trigger language plpgsql as $$
begin
  new.alias_name:=public.normalize_station_text(new.alias_name);
  new.standard_city_name:=regexp_replace(public.normalize_station_text(new.standard_city_name),'市$','');
  if new.alias_name='' or new.standard_city_name='' then raise exception '城市别名数据无效'; end if;
  new.updated_at:=now();return new;
end; $$;
drop trigger if exists city_alias_normalize on public.city_alias;
create trigger city_alias_normalize before insert or update on public.city_alias for each row execute function public.guard_city_alias();

insert into public.city_alias(alias_name,standard_city_name)
select distinct city_name||'市',city_name from public.station_dict where city_name<>''
on conflict(alias_name) do update set standard_city_name=excluded.standard_city_name,updated_at=now();

create or replace function public.get_station_list(p_city_name text,p_transport_type text)
returns table(station_name text,station_short_name text)
language sql stable security definer set search_path=public as $$
  with cleaned as(select regexp_replace(public.normalize_station_text(p_city_name),'市$','') city),
  resolved as(
    select coalesce((select ca.standard_city_name from public.city_alias ca,cleaned c where ca.alias_name=public.normalize_station_text(p_city_name) limit 1),(select city from cleaned)) city
  )
  select d.station_name,d.station_short_name from public.station_dict d,resolved r
  where d.city_name=r.city and d.transport_type=p_transport_type
  order by d.station_short_name,d.station_name
$$;
revoke all on function public.get_station_list(text,text) from public;
grant execute on function public.get_station_list(text,text) to anon,authenticated,service_role;

create or replace function public.get_station_cities()
returns table(city_name text) language sql stable security definer set search_path=public as $$
  select distinct d.city_name from public.station_dict d order by d.city_name
$$;
revoke all on function public.get_station_cities() from public;
grant execute on function public.get_station_cities() to anon,authenticated,service_role;

create or replace function public.replace_city_aliases(p_items jsonb)
returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer;
begin
  if not public.is_system_admin() then raise exception '仅超级管理员可维护城市别名'; end if;
  if jsonb_typeof(p_items) is distinct from 'array' then raise exception '城市别名格式错误'; end if;
  create temporary table tmp_city_alias(alias_name text,standard_city_name text) on commit drop;
  insert into tmp_city_alias select public.normalize_station_text(alias),regexp_replace(public.normalize_station_text(city),'市$','') from jsonb_to_recordset(p_items) as x(alias text,city text);
  if exists(select 1 from tmp_city_alias where alias_name='' or standard_city_name='') then raise exception '城市别名包含无效数据'; end if;
  delete from public.city_alias;
  insert into public.city_alias(alias_name,standard_city_name) select distinct on(alias_name) alias_name,standard_city_name from tmp_city_alias order by alias_name;
  get diagnostics v_count=row_count;return v_count;
end; $$;
revoke all on function public.replace_city_aliases(jsonb) from public;
grant execute on function public.replace_city_aliases(jsonb) to authenticated;

create or replace function public.replace_station_dictionary(p_items jsonb)
returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer;
begin
  if not public.is_system_admin() then raise exception '仅超级管理员可维护场站字典'; end if;
  if jsonb_typeof(p_items) is distinct from 'array' then raise exception '场站字典格式错误'; end if;
  create temporary table tmp_station_dict(city_name text,transport_type text,station_name text,station_short_name text) on commit drop;
  insert into tmp_station_dict
  select regexp_replace(public.normalize_station_text(city),'市$',''),public.normalize_station_text(type),public.normalize_station_text(name),coalesce(nullif(public.normalize_station_text(short_name),''),public.normalize_station_text(name))
  from jsonb_to_recordset(p_items) as x(city text,type text,name text,short_name text);
  if exists(select 1 from tmp_station_dict where city_name='' or station_name='' or transport_type not in('PLANE','HIGH_SPEED_RAIL')) then raise exception '场站字典包含无效数据'; end if;
  delete from public.station_dict;
  insert into public.station_dict(city_name,transport_type,station_name,station_short_name)
  select distinct city_name,transport_type,station_name,station_short_name from tmp_station_dict;
  get diagnostics v_count=row_count;return v_count;
end; $$;
revoke all on function public.replace_station_dictionary(jsonb) from public;
grant execute on function public.replace_station_dictionary(jsonb) to authenticated;

create or replace function public.sync_verify_highlight_fields()
returns trigger language plpgsql as $$
begin
  if jsonb_typeof(new.custom_fields->'_travelVerifiedHighlights')='array' then
    new.verify_highlight_fields:=new.custom_fields->'_travelVerifiedHighlights';
  elsif new.verify_highlight_fields is null then new.verify_highlight_fields:='[]'::jsonb;
  end if;
  if new.depart_transport_type='LOCAL_ATTEND' then new.depart_station:=null;end if;
  if new.arrive_transport_type='LOCAL_ATTEND' then new.arrive_station:=null;end if;
  if new.return_depart_transport_type='LOCAL_ATTEND' then new.return_depart_station:=null;end if;
  if new.return_arrive_transport_type='LOCAL_ATTEND' then new.return_arrive_station:=null;end if;
  return new;
end; $$;
drop trigger if exists attendees_sync_verify_highlights on public.attendees;
create trigger attendees_sync_verify_highlights before insert or update of custom_fields,verify_highlight_fields,depart_transport_type,depart_station,arrive_transport_type,arrive_station,return_depart_transport_type,return_depart_station,return_arrive_transport_type,return_arrive_station on public.attendees for each row execute function public.sync_verify_highlight_fields();

notify pgrst,'reload schema';
