-- PostgreSQL adaptation of the requested participant_list / station_dict schema.
-- The production roster table is public.attendees; legacy return_* fields remain compatible.
alter table public.attendees add column if not exists return_depart_date date;
alter table public.attendees add column if not exists return_depart_city text;
alter table public.attendees add column if not exists return_depart_transport_type text;
alter table public.attendees add column if not exists return_depart_station text;
alter table public.attendees add column if not exists return_arrive_date date;
alter table public.attendees add column if not exists return_arrive_city text;
alter table public.attendees add column if not exists return_arrive_transport_type text;
alter table public.attendees add column if not exists return_arrive_station text;

alter table public.attendees disable trigger attendees_audit_change;
update public.attendees set
  return_depart_date=coalesce(return_depart_date,return_date),
  return_depart_transport_type=coalesce(return_depart_transport_type,case when coalesce(return_no,'') ilike '%本地参会%' then 'LOCAL_ATTEND' when coalesce(return_no,'') ~* '^[GDCZTKYSL][0-9]+' then 'HIGH_SPEED_RAIL' else 'PLANE' end),
  return_depart_city=coalesce(nullif(return_depart_city,''),regexp_replace(regexp_replace(coalesce(return_from,''),'国际机场.*$|机场.*$','','g'),'火车站$|高铁站$|站$','','g')),
  return_depart_station=case when coalesce(return_depart_transport_type,case when coalesce(return_no,'') ilike '%本地参会%' then 'LOCAL_ATTEND' when coalesce(return_no,'') ~* '^[GDCZTKYSL][0-9]+' then 'HIGH_SPEED_RAIL' else 'PLANE' end)='LOCAL_ATTEND' then null else coalesce(nullif(return_depart_station,''),nullif(return_from,'')) end,
  return_arrive_date=coalesce(return_arrive_date,return_date),
  return_arrive_transport_type=coalesce(return_arrive_transport_type,case when coalesce(return_no,'') ilike '%本地参会%' then 'LOCAL_ATTEND' when coalesce(return_no,'') ~* '^[GDCZTKYSL][0-9]+' then 'HIGH_SPEED_RAIL' else 'PLANE' end),
  return_arrive_city=coalesce(nullif(return_arrive_city,''),regexp_replace(regexp_replace(coalesce(return_to,''),'国际机场.*$|机场.*$','','g'),'火车站$|高铁站$|站$','','g')),
  return_arrive_station=case when coalesce(return_arrive_transport_type,case when coalesce(return_no,'') ilike '%本地参会%' then 'LOCAL_ATTEND' when coalesce(return_no,'') ~* '^[GDCZTKYSL][0-9]+' then 'HIGH_SPEED_RAIL' else 'PLANE' end)='LOCAL_ATTEND' then null else coalesce(nullif(return_arrive_station,''),nullif(return_to,'')) end;
alter table public.attendees enable trigger attendees_audit_change;

alter table public.attendees drop constraint if exists attendees_return_depart_transport_type_check;
alter table public.attendees add constraint attendees_return_depart_transport_type_check check (return_depart_transport_type is null or return_depart_transport_type in ('PLANE','HIGH_SPEED_RAIL','LOCAL_ATTEND'));
alter table public.attendees drop constraint if exists attendees_return_arrive_transport_type_check;
alter table public.attendees add constraint attendees_return_arrive_transport_type_check check (return_arrive_transport_type is null or return_arrive_transport_type in ('PLANE','HIGH_SPEED_RAIL','LOCAL_ATTEND'));
alter table public.attendees drop constraint if exists attendees_local_return_depart_station_check;
alter table public.attendees add constraint attendees_local_return_depart_station_check check (return_depart_transport_type is distinct from 'LOCAL_ATTEND' or return_depart_station is null);
alter table public.attendees drop constraint if exists attendees_local_return_arrive_station_check;
alter table public.attendees add constraint attendees_local_return_arrive_station_check check (return_arrive_transport_type is distinct from 'LOCAL_ATTEND' or return_arrive_station is null);
create index if not exists attendees_depart_city_idx on public.attendees(depart_city);
create index if not exists attendees_arrive_city_idx on public.attendees(arrive_city);

create table if not exists public.station_dict(
  id bigint generated by default as identity primary key,
  city_name text not null,
  transport_type text not null check(transport_type in ('PLANE','HIGH_SPEED_RAIL')),
  station_name text not null,
  station_short_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(city_name,transport_type,station_name)
);
create index if not exists station_dict_city_transport_idx on public.station_dict(city_name,transport_type);
alter table public.station_dict enable row level security;
drop policy if exists station_dict_read on public.station_dict;
create policy station_dict_read on public.station_dict for select to authenticated using (true);
drop policy if exists station_dict_admin_write on public.station_dict;
create policy station_dict_admin_write on public.station_dict for all to authenticated using (public.is_system_admin()) with check (public.is_system_admin());

insert into public.station_dict(city_name,transport_type,station_name,station_short_name) values
('上海','PLANE','上海虹桥国际机场T1航站楼','上海虹桥 T1'),('上海','PLANE','上海虹桥国际机场T2航站楼','上海虹桥 T2'),('上海','PLANE','上海浦东国际机场T1航站楼','上海浦东 T1'),('上海','PLANE','上海浦东国际机场T2航站楼','上海浦东 T2'),
('上海','HIGH_SPEED_RAIL','上海虹桥站','上海虹桥站'),('上海','HIGH_SPEED_RAIL','上海站','上海站'),('上海','HIGH_SPEED_RAIL','上海西站','上海西站'),('上海','HIGH_SPEED_RAIL','上海松江南站','上海松江南站'),('上海','HIGH_SPEED_RAIL','安亭站','安亭站'),('上海','HIGH_SPEED_RAIL','安亭北站','安亭北站'),
('北京','PLANE','北京首都国际机场T1航站楼','北京首都 T1'),('北京','PLANE','北京首都国际机场T2航站楼','北京首都 T2'),('北京','PLANE','北京首都国际机场T3航站楼','北京首都 T3'),('北京','PLANE','北京大兴国际机场','北京大兴'),
('北京','HIGH_SPEED_RAIL','北京南站','北京南站'),('北京','HIGH_SPEED_RAIL','北京西站','北京西站'),('北京','HIGH_SPEED_RAIL','北京站','北京站'),('北京','HIGH_SPEED_RAIL','北京朝阳站','北京朝阳站'),('北京','HIGH_SPEED_RAIL','北京丰台站','北京丰台站'),('北京','HIGH_SPEED_RAIL','清河站','清河站'),
('大连','PLANE','大连周水子国际机场','大连周水子'),('大连','HIGH_SPEED_RAIL','大连站','大连站'),('大连','HIGH_SPEED_RAIL','大连北站','大连北站'),
('福州','PLANE','福州长乐国际机场','福州长乐'),('福州','HIGH_SPEED_RAIL','福州站','福州站'),('福州','HIGH_SPEED_RAIL','福州南站','福州南站')
on conflict(city_name,transport_type,station_name) do update set station_short_name=excluded.station_short_name,updated_at=now();

create or replace function public.replace_station_dictionary(p_items jsonb)
returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer;
begin
  if not public.is_system_admin() then raise exception '仅超级管理员可维护场站字典'; end if;
  if jsonb_typeof(p_items) is distinct from 'array' then raise exception '场站字典格式错误'; end if;
  create temporary table tmp_station_dict(city_name text,transport_type text,station_name text,station_short_name text) on commit drop;
  insert into tmp_station_dict
  select btrim(city),btrim(type),btrim(name),nullif(btrim(short_name),'') from jsonb_to_recordset(p_items) as x(city text,type text,name text,short_name text);
  if exists(select 1 from tmp_station_dict where city_name='' or station_name='' or transport_type not in ('PLANE','HIGH_SPEED_RAIL')) then raise exception '场站字典包含无效数据'; end if;
  delete from public.station_dict;
  insert into public.station_dict(city_name,transport_type,station_name,station_short_name)
  select distinct city_name,transport_type,station_name,station_short_name from tmp_station_dict;
  get diagnostics v_count=row_count; return v_count;
end; $$;
revoke all on function public.replace_station_dictionary(jsonb) from public;
grant execute on function public.replace_station_dictionary(jsonb) to authenticated;

create or replace function public.guard_return_journey_columns()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if exists(select 1 from public.column_locks where meeting_id=old.meeting_id and field_group='return' and locked)
     and row(new.return_depart_date,new.return_depart_city,new.return_depart_transport_type,new.return_depart_station,new.return_arrive_date,new.return_arrive_city,new.return_arrive_transport_type,new.return_arrive_station)
       is distinct from row(old.return_depart_date,old.return_depart_city,old.return_depart_transport_type,old.return_depart_station,old.return_arrive_date,old.return_arrive_city,old.return_arrive_transport_type,old.return_arrive_station)
     and not public.is_system_admin() then raise exception '返程整列已锁定'; end if;
  if new.return_depart_transport_type='LOCAL_ATTEND' then new.return_depart_station:=null; end if;
  if new.return_arrive_transport_type='LOCAL_ATTEND' then new.return_arrive_station:=null; end if;
  return new;
end; $$;
drop trigger if exists attendees_guard_return_journey on public.attendees;
create trigger attendees_guard_return_journey before update on public.attendees for each row execute function public.guard_return_journey_columns();

notify pgrst, 'reload schema';
