create table if not exists public.dictionary_sync_runs(
  id bigint generated by default as identity primary key,
  status text not null check(status in ('running','success','failed')),
  railway_source text not null default 'China Railway 12306 station_name.js',
  airport_source text not null default 'CAAC transport airport directory',
  airport_source_as_of date,
  railway_count integer not null default 0,
  airport_count integer not null default 0,
  station_upsert_count integer not null default 0,
  alias_upsert_count integer not null default 0,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists dictionary_sync_runs_started_at_idx
on public.dictionary_sync_runs(started_at desc);

alter table public.dictionary_sync_runs enable row level security;
grant select on public.dictionary_sync_runs to authenticated;
grant all on public.dictionary_sync_runs to service_role;
grant usage,select on sequence public.dictionary_sync_runs_id_seq to service_role;

drop policy if exists dictionary_sync_runs_admin_read on public.dictionary_sync_runs;
create policy dictionary_sync_runs_admin_read on public.dictionary_sync_runs
for select to authenticated using(public.is_system_admin());

notify pgrst,'reload schema';
